name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v7

      - name: Maven test
        run: mvn test

      - name: checkstyle test
        run: checkstyle:checkstyle  

